# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call(`_MultiskewBART_rmvnorm`, mean, Precision)
}

rlgam <- function(shape) {
    .Call(`_MultiskewBART_rlgam`, shape)
}

update_z_multi_2 <- function(Y, mu, Sigma, Z_0) {
    .Call(`_MultiskewBART_update_z_multi_2`, Y, mu, Sigma, Z_0)
}

